language: php

php:
  - 5.6

env:
  - SYMFONY_VERSION=2.8.*

before_script:
  - travis_retry composer self-update
  - composer require --prefer-source --dev symfony/symfony:${SYMFONY_VERSION}

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

script:
  - mkdir -p build/logs
  - phpunit --coverage-text --coverage-clover=coverage.clover
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls -v